import { StyleSheet } from "react-native";

export const stylesCourse_lesson = StyleSheet.create({
  container: {},
  // from stylesTest
  arrows: {
    position: "absolute",
    bottom: "100%",
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },

  navTopArrowView: {
    position: "absolute",
    bottom: -10,
  },

  navTopArrow: {
    width: 10,
    height: 10,
    resizeMode: "contain",
  },

  navTopModal: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 3,
  },
  navTopBg: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },

  navTopModalIn: {
    padding: 0,
    width: "100%",
    borderTopWidth: 2.5,
    borderTopColor: "#ebebeb",
  },

  navTopModalText: {
    textAlign: "center",
  },
  // end stylesTest
  bgCourse: {
    backgroundColor: "#ffffff",
  },
  card: {
    width: 70,
    height: 56,
    marginBottom: "5%",
    borderRadius: 300,
    alignItems: "center",
    justifyContent: "center",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 0,
  },

  infoCourseSubject: {
    position: "absolute",
    top: "12%",
    left: "5%",
    right: "5%",
    width: "90%",
    height: 95,
    marginTop: "2%",
    flexDirection: "row",
    zIndex: 1,
  },

  cardPressed: {
    shadowOffset: { width: 0, height: 0 },
    transform: [{ translateY: 4 }],
  },
  bgGry: {
    backgroundColor: "#e5e5e5",
    shadowColor: "#b7b7b7",
  },
  bgGryPressed: {
    backgroundColor: "#f9f9f9",
    borderColor: "#d8d8d8",
  },
  contentFlashCards: {
    flexDirection: "column",
    // flexWrap: "wrap",
    // justifyContent: "center",
    // alignItems: "center",
    // alignContent: "center",
  },

  infoCourseTitle: {
    color: "white",
    fontSize: 19,
    width: "80%",
    marginLeft: "5%",
    textTransform: "uppercase",
    fontWeight: "600",
  },
  cardCategoryTitle: {
    width: "73%",
    height: "100%",
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    justifyContent: "center",
    alignSelf: "center",
    textAlign: "center",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 0,
  },
  infoCourseBtn: {
    width: "27%",
    height: "100%",
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    justifyContent: "center",
    alignSelf: "center",
    textAlign: "center",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 0,
  },
  infoCourseTxtSubCat: {
    color: "#d1ffb1",
    fontSize: 15,
    width: "80%",
    marginLeft: "5%",
    textTransform: "uppercase",
    fontWeight: "700",
  },
  infoCategoryImg: {
    width: "30%",
    height: "30%",
    resizeMode: "contain",
    alignSelf: "center",
  },
  modal: {
    height: "73%",
    backgroundColor: "#efefef",
    borderRadius: 10,
  },
  modalCourseContent: {
    paddingLeft: "4%",
    paddingRight: "4%",
    paddingBottom: "4%",
  },
  closeModalCourse: {
    marginTop: "2%",
    padding: 10,
  },
  courseCatImg: {
    width: 130,
    height: 130,
    resizeMode: "contain",
  },
  infoCatTitle: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 25,
    paddingTop: "5%",
    paddingLeft: "2%",
    paddingRight: "5%",
    paddingBottom: "5%",
  },
  titleLessonCat: {
    width: "62%",
    justifyContent: "center",
    paddingLeft: "4%",
  },
  titleLessonCatTxt: {
    fontSize: 20,
    color: "#212121",
    fontWeight: "500",
  },
  titleLessonCatSubject: {
    fontSize: 16,
    color: "#6949FF",
  },
  courseDetCatImg: {
    width: 57,
    height: 57,
    resizeMode: "contain",
  },
  infoDetExtraCat: {
    backgroundColor: "white",
    borderRadius: 25,
    paddingTop: "6%",
    paddingLeft: "6%",
    paddingRight: "6%",
    paddingBottom: "6%",
    marginTop: "5%",
  },
  infoDetCatTitle: {
    flexDirection: "row",
    marginBottom: "0",
  },
  titleDetLessonCat: {
    width: "62%",
    justifyContent: "center",
    paddingLeft: "5%",
  },
  titleDetLessonCatSubject: {
    fontSize: 17.5,
    color: "#212121",
    fontWeight: "500",
    textTransform: "uppercase",
  },
  titleDetLessonCatTxt: {
    fontSize: 16,
    color: "#616161",
  },
  horizontalLine: {
    width: "90%",
    alignSelf: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#EEEEEE",
    marginVertical: "7%",
  },
  headerModalCat: {
    flexDirection: "row",
  },
  headerTitleModalCat: {
    justifyContent: "center",
    alignSelf: "center",
  },
  headerTitleModalCatTxt: {
    fontSize: 18,
    color: "#212121",
    textTransform: "uppercase",
    alignSelf: "center",
    textAlign: "center",
    marginTop: "1%",
  },

  categoryTitleBg: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
    marginVertical: "15%",
  },
  hrLine: {
    flex: 1,
    height: 2,
    backgroundColor: "#ababab",
    marginHorizontal: "4.5%",
  },
  categoryTitle: {
    maxWidth: "50%",
    fontSize: 20,
    textAlign: "center",
    fontWeight: "bold",
    color: "#ababab",
  },
  iconFlash: {
    color: "#ababab",
  },
  startImg: {
    width: 107,
    height: 57,
    resizeMode: "contain",
    alignSelf: "center",
  },
  elCourseImg: {
    width: 150,
    height: 220,
    position: "absolute",
    right: 25,
    top: 120,
    resizeMode: "contain",
    alignSelf: "center",
  },
  containerSentences: {
    backgroundColor: "#ffffff",
    paddingTop: "6%",
    paddingBottom: "11%",
  },
  titleh5: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#7ec81a",
    textAlign: "center",
  },
  titleh6: {
    fontSize: 18,
    fontWeight: 600,
    marginBottom: 20,
    color: "#9f9f9f",
    textAlign: "center",
  },
  titleh7: {
    fontSize: 24,
    fontWeight: '500',
    color: "#FF9600",
    marginTop: 30,
    textAlign: "center",
    alignItems: "center",
  },
  rowBlockSentences: {
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
  },
  resultProgressBar: {
    fontSize: 37,
    fontWeight: "bold",
    color: "#748895",
    textAlign: "center",
  },
  containerResultDataSce: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  containerResultDataSce1: {
    flexDirection: "row",
    justifyContent: "center",
  },
  rowContainerLanguageSelect:{
    flexDirection: "row",
  },
  containerLanguageSelect: {
    justifyContent: "center",
    marginLeft: '6%',
    alignItems: 'flex-start',
  },

  textLangSelect: {
    fontSize: 16,
    marginTop: '0%',
    color: "#545b62",
    fontWeight: '700',
    textAlign: 'center',
  },
  cardDataSce: {
    width: "42%",
    marginTop: '7%',
    marginHorizontal: '2%',
    paddingHorizontal: '3%',
    paddingTop: '8%',
    paddingBottom: '8%',
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 0,
  },
  cardDataDayCurrent:{
    width: "45%",
    paddingTop: '4%',
    paddingBottom: '4%',
    alignItems: "center",
    justifyContent: "center",
    borderRightWidth: 1,
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderLeftWidth: 2,
    borderColor: '#d8d8d8',
    borderTopLeftRadius: 10, 
    borderTopRightRadius: 0, 
    borderBottomLeftRadius: 10, 
    borderBottomRightRadius: 0,
  },
  cardDataDayLong:{
    width: "45%",
    paddingTop: '4%',
    paddingBottom: '4%',
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderLeftWidth: 1,
    borderRightWidth: 2,
    borderColor: '#d8d8d8',
    borderTopLeftRadius: 0, 
    borderTopRightRadius: 10, 
    borderBottomLeftRadius: 0, 
    borderBottomRightRadius: 10,
  },
  imageAnalyticsDay:{
    width: 60,
    height: 60,
    resizeMode: "contain",
    alignSelf: "center",
  },
  flagsLang:{
    width: 100,
    height: 100,
    resizeMode: "contain",
  },
  imageAnalyticsDayCheck:{
    width: 30,
    height: 30,
    resizeMode: "contain",
    alignSelf: "center",
    marginTop: 8,
  },
  percentage: {
    fontSize: 35,
    fontWeight: "bold",
    color: "#7ec81a",
    textAlign: 'center',
  },
  timeframe: {
    fontSize: 16,
    marginTop: '3%',
    color: "#545b62",
    textAlign: 'center',
  },
  dayW: {
    fontSize: 19,
    fontWeight: "bold",
    marginTop: '3%',
    color: "#FF9600",
    textAlign: 'center',
  },
  boxDay:{
    marginTop: '8%',
    marginLeft: '2.7%',
    marginRight: '2.7%',
  },
  percentage1: {
    fontSize: 19,
    fontWeight: "bold",
    color: "#4b4b4b",
    marginTop: '4%',
    textAlign: 'center',
  },
  timeframe1: {
    fontSize: 16,
    marginTop: '0%',
    color: "#545b62",
  },
  levelRoughly: {
    fontSize: 20,
    fontWeight: "500",
    color: "#007bff",
    marginBottom: 5,
    textAlign: "center",
  },
  messageRoughly: {
    fontSize: 16,
    fontStyle: "italic",
    textAlign: "center",
  },
});
