import { StyleSheet } from "react-native";

export const stylesCourse_lesson = StyleSheet.create({
  videoContainer: {
    flex: 1,
    width: "100%",
    height: "37%",
    borderRadius: 12,
  },
  groupBtnQuizFinish: {
    flexDirection: "row",
  },
  video: {
    width: "100%",
    height: "100%",
    borderRadius: 12,
    resizeMode: "cover",
  },
  btnabs: {
    position: "absolute",
    backgroundColor: "red",
    width: "30%",
    bottom: 80,
    left: 40,
  },
  carousel: {
    height: "70%",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  gradient: {
    flex: 1,
  },
  row: {
    flexDirection: "row",
    marginTop: "10%",
    height: "7%",
  },
  slideBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  slide: {
    backgroundColor: "#fff",
    borderRadius: 10,
    height: "100%",
    padding: 20,
    alignSelf: "center",
  },
  slideIn: {
    flex: 1,
    justifyContent: "center",
  },
  swiperContent: {
    height: "100%",
    backgroundColor: "white",
  },

  containerVideoLesson: {
    width: "90%",
    height: "50%",
  },
  containerAudioLesson: {
    width: "55%",
    aspectRatio: 1,
    backgroundColor: "#27cad4",
    borderRadius: 1000,
    justifyContent: "center",
    alignItems: "center",
  },
  containerQuizInput: {
    width: "55%",
    backgroundColor: "#27cad4",
    justifyContent: "center",
    alignItems: "center",
  },
  progressBarContainer: {
    flex: 1,
    backgroundColor: "#3a464e",
    borderRadius: 10,
    marginRight: "5%",
    alignSelf: "center",
    height: "40%",
  },
  progressBar: {
    flex: 1,
    backgroundColor: "#ffeb3b",
    borderRadius: 10,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    width: "14%",
    height: "100%",
    paddingLeft: "2%",
    paddingRight: "1%",
    paddingTop: "1%",
    textAlign: "center",
  },
  image: {
    width: "50%",
    height: "50%",
    objectFit: "contain",
  },
  audio: {
    color: "white",
  },
  textCourse: {
    width: "80%",
    height: "20%",
    borderRadius: 14,
    marginTop: "5%",
    justifyContent: "center",
    backgroundColor: "white",
  },
  textOrig: {
    fontSize: 22,
    color: "#303030",
    textAlign: "center",
  },
  textLearn: {
    fontSize: 18,
    color: "#404040",
    textAlign: "center",
    fontStyle: "italic",
  },
  swiperButtonsContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingHorizontal: "5%",
    paddingVertical: "8%",
  },
  button: {
    paddingHorizontal: 20,
    paddingVertical: 30,
    marginRight: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#ccc",

    width: "48%",
    // paddingVertical: 18,
    // paddingHorizontal: 32,
    alignItems: "center",
    borderRadius: 14,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 0,
  },
  quizBtn: {
    width: "80%",
    marginTop: "7%",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "flex-start",
    alignContent: "flex-start",
  },
  quizBtnTyping: {
    width: "80%",
    marginTop: "7%",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
  },
  quizButtonTyping: {
    width: "20%",
    paddingVertical: 18,
    alignItems: "center",
    borderRadius: 14,
    marginBottom: "4%",
    marginRight: "4%",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 0,
  },
  input: {
    paddingVertical: 18,
    alignItems: "center",
  },
  bgGroupTitleCourse1: {
    marginTop: "9%",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 10,
  },
  videoContainerGroup: {
    width: "100%",
    minHeight: "11%",
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
  },
  inputView: {
    borderBottomWidth: 2.1,
    borderColor: "#e0e0e0",
    flexDirection: "row",
    borderLeftWidth: 2.1,
    borderRightWidth: 2.1,
    paddingLeft: 12,
  },
  inputContainer1: {
    borderTopWidth: 2.1,
    borderRadius: 14,
    paddingBottom: 17,
    paddingTop: 17,
    paddingRight: 12,
    marginBottom: 12,
  },
  base_title: {
    color: "#212121",
    fontSize: 16,
    textAlign: "center",
  },

  groupTitleCourse1: {
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderColor: "#E0E0E0",
    borderBottomWidth: 0,
    borderBottomWidth: 1,
    paddingHorizontal: "3%",
  },
  groupTitleCourse2: {
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    borderColor: "#E0E0E0",
    paddingHorizontal: "3%",
  },
  groupTitleLesson: {
    color: "#616161",
    fontSize: 16,
    textAlign: "center",
    width: "100%",
    marginVertical: "6.5%",
  },
  groupQuizBtn: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: "9%",
  },
  btnQuizStyle: {
    color: "#616161",
    fontSize: 16,
    textAlign: "center",
    width: "100%",
    paddingVertical: "10%",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  btnQuizPositionCa: {
    paddingVertical: "4%",
    paddingHorizontal: "4%",
    marginRight: "3%",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  btnQuizStyleCa: {
    color: "#616161",
    fontSize: 16,
    textAlign: "center",
  },
  btnQuizPosition1: {
    width: "50%",
    paddingRight: "2.5%",
    marginBottom: "2.5%",
  },
  btnQuizPosition2: {
    width: "50%",
    paddingLeft: "2.5%",
    marginBottom: "2.5%",
  },
  variantImageStyle: {
    width: "100%",
    height: "37%",
    resizeMode: "cover",
    borderRadius: 10,
  },
  imageContainerGroup: {
    backgroundColor: "red",
    width: "100%",
    height: "37%",
    borderRadius: 14,
    justifyContent: "center",
  },
  baseTitleImg: {
    color: "black",
    fontWeight: "600",
    fontSize: 19,
    textAlign: "center",
    width: "100%",
    marginVertical: "6.5%",
  },
  audioWord: {},
  succesImg: {
    alignSelf: "center",
    marginBottom: "2.9%",
    width: "100%",
    height: "50%",
    resizeMode: "contain",
    marginTop: "4%",
  },
  modalContainer: {
    width: "100%",
    height: "100%",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "white",
    paddingTop: "10%",
    alignItems: "flex-start",
    alignContent: "flex-start",
    zIndex: 999,
  },
  modalClose: {
    height: "10%",
    paddingRight: "5%",
    paddingLeft: "2%",
    alignItems: "flex-start",
    alignContent: "flex-start",
  },
  succesText: {
    color: "#343541",
    fontSize: 18,
    fontWeight: "600",
    marginBottom: "20%",
    textAlign: "center",
  },
  modalText: {
    textTransform: "uppercase",
    color: "white",
    fontSize: 18,
    fontWeight: "600",
  },
  modalContainerCenter: {
    width: "100%",
    paddingHorizontal: "5%",
    alignSelf: "center",
    paddingTop: "4%",
  },

  buttonGenQuiz: {
    alignSelf: "center",
  },

  modalView: {
    width: "100%",
    height: "100%",
    paddingTop: "0%",
    // alignItems: "flex-start",
    alignContent: "flex-start",
    backgroundColor: "white",
    alignItems: "center",
  },
  modalView: {
    width: "100%",
    height: "100%",
    paddingTop: "0%",
    // alignItems: "flex-start",
    alignContent: "flex-start",
    backgroundColor: "white",
    alignItems: "center",
  },
  resultQuizData: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
    marginBottom: "12%",
  },
  quizDataContainer: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#12D18E",
    borderRadius: 10,
  },
  quizDataContainer3: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#FB9400",
    borderRadius: 10,
  },
  quizDatamlmr: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#FF5A5F",
    borderRadius: 10,
    marginHorizontal: "3%",
  },
  quizDataBackground1: {
    backgroundColor: "#12D18E",
    borderTopLeftRadius: 9,
    borderTopRightRadius: 9,
    paddingVertical: "10%",
  },
  quizDataBackground2: {
    backgroundColor: "#FF5A5F",
    borderTopLeftRadius: 9,
    borderTopRightRadius: 9,
    paddingVertical: "10%",
  },
  quizDataBackground3: {
    backgroundColor: "#FB9400",
    borderTopLeftRadius: 9,
    borderTopRightRadius: 9,
    paddingVertical: "10%",
  },

  quizDataLabel: {
    color: "white",
    fontSize: 18,
    textAlign: "center",
  },

  quizDataCount: {
    color: "#212121",
    fontSize: 24,
    paddingVertical: "10%",
    textAlign: "center",
  },

  succesImgQuiz: {
    alignSelf: "center",
    marginBottom: "10%",
    width: "100%",
    height: "47%",
    resizeMode: "contain",
  },

  answerFlashcard: {
    textTransform: "uppercase",
    fontWeight: "600",
    fontSize: 17,
    color: "#8895bc",
  },

  buttonRestartQuiz: {
    width: "30%",
    paddingVertical: 18,
    paddingHorizontal: 32,
    alignItems: "center",
    borderRadius: 14,
    marginBottom: 20,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 0,
  },
  buttonEndQuiz: {
    width: "67%",
    marginLeft: "3%",
    paddingVertical: 18,
    paddingHorizontal: 32,
    alignItems: "center",
    borderRadius: 14,
    marginBottom: 20,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 0,
  },
});
